# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "terragrunt/environments/dev/cluster/terraform.tfstate"
    resource_group_name  = "rg-tfstate"
    storage_account_name = "tfstatebackend0003"
  }
}
